# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metabet_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='result',
            field=models.CharField(default='U', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set([('home_team', 'away_team', 'date')]),
        ),
    ]
