# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metabet_core', '0002_auto_20160917_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=9)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metabet_core.Competition')),
            ],
        ),
        migrations.AlterField(
            model_name='teamsnapshot',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metabet_core.CompetitionSeason'),
        ),
        migrations.AlterUniqueTogether(
            name='competitionseason',
            unique_together=set([('competition', 'season')]),
        ),
    ]
